spring:
  profiles:
    include: real-db, mail, jwt, aws, aws-credential

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      enabled: true